{% set version = "1.3.6" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hdf5r
  version: {{ version|replace("-", "_") }}

source:
  fn: hdf5r_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/hdf5r_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/hdf5r/hdf5r_{{ version }}.tar.gz
  sha256: 34a0195e0b7c17c12254236645b76c26b23976382d86462a0785899ea7b1319a

build:
  merge_build_host: true  # [win]
  number: 1
  script: R CMD INSTALL --build .
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - hdf5
    - r-base
    - r-r6
    - r-bit64
  run:
    - hdf5
    - r-base
    - r-r6
    - r-bit64

test:
  commands:
    - $R -e "library('hdf5r')"  # [not win]
    - "\"%R%\" -e \"library('hdf5r')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/hdf5r
  license: Apache 2.0
  license_file: LICENSE
  summary: HDF5 is a data model, library and file format for storing  and managing large amounts of data. This package provides a nearly feature complete, object oriented  wrapper for the HDF5 API

extra:
  recipe-maintainers:
    - ocefpaf
