{% set version = "1.0.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hdf5r
  version: {{ version|replace("-", "_") }}

source:
  fn: hdf5r_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/hdf5r_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/hdf5r/hdf5r_{{ version }}.tar.gz
  sha256: 32f35dc26809a7e9b9335e0dc24369cf87f4c6deb430b2d9d019450a10164240

build:
  number: 0
  script: R CMD INSTALL --build .
  skip: True  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - hdf5 1.10.1
    - r-base
    - r-r6
    - r-bit64
    - posix  # [win]
    - {{native}}toolchain  # [win]
    - gcc  # [not win]
  run:
    - hdf5 1.10.1
    - r-base
    - r-r6
    - r-bit64
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('hdf5r')"  # [not win]
    - "\"%R%\" -e \"library('hdf5r')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/hdf5r
  license: Apache 2.0
  license_file: LICENSE
  summary: HDF5 is a data model, library and file format for storing  and managing large
    amounts of data. This package provides a nearly feature complete, object oriented  wrapper
    for the HDF5 API

extra:
  recipe-maintainers:
    - ocefpaf
