{% set version = "1.3.10" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-hdf5r
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/hdf5r_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/hdf5r/hdf5r_{{ version }}.tar.gz
  sha256: 92496e0693a27c0a1c8caba671c51fcecc3a120f8ef7eb0cb3cd686a3e49124e
  patches:
    - patches/0001-minimal-libs-ucrt.patch

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-bit64                      # [build_platform != target_platform]
    - r-r6                         # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - hdf5
    - r-base
    - r-bit64
    - r-r6
  run:
    - r-base
    - r-bit64
    - r-r6

test:
  commands:
    - $R -e "library('hdf5r')"  # [not win]
    - "\"%R%\" -e \"library('hdf5r')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/hdf5r
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: |
    HDF5 is a data model, library and file format for storing  and managing 
    large amounts of data. This package provides a nearly feature complete, 
    object oriented  wrapper for the HDF5 API

extra:
  recipe-maintainers:
    - ocefpaf
    - conda-forge/r
