# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Y3lE93gd28k/Rtb8ZCaHuKooP946swByIq37pG5cryEK0yXdAiDgOnlW3ZpJzOIULEIA9VFs+GgNCx+RiKKwsJeUglOT/5dfvdm/fn2dlHfwGFsFMU0uaYzPcoErnbLr6eLhaAUyKFcM9jcE6KzhgYODgPiC2Old1ydaszrOcZfvVvVW8aBU1vatAYDSM9IZlqc7tWeAy023RUDl6X5QvBmrbKJL2VGwdZ0SIXvaNCJBde+1Zt4VcL3igFhaEOPImPUXVkusxQ95QtXUysn9Gn0RgGkXc/9kgx4Gap2ixHbnJovmPOrNE+KoFsMHkh1+81YWpSKBQPPX28XPbdl1hWClt3agC2Ru/lAAx9fit0uByYW1my9IiUB5b/D0C+57ZNs7Buk8bo/7GTi6rlPi2Pt3MIYVoOuSUjONtrDN9nQW8yoWdkju6sj2R4drH6pjPEcWQjja+uK+GyjUB2n0iidzxL0HybswGVAv6m44CWwROt9+AzJF9o1ArszxCUOGOy0NOnTpHwEjkr9smk4BtNhov3cOooABAwCzKtUV9Wp7cCigaBdqGmSJKBYXrqltAMdbWAJzGJrKd6CxVYvXCbsJWKZGpomVhX8pusc8AMAt1tJ9AnxNARo2/cRTCZ7H41HosX25RQoAdLnr78LGSfwbiUhFJBcrLBK702eIoYQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
