appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Y3lE93gd28k/Rtb8ZCaHuKooP946swByIq37pG5cryEK0yXdAiDgOnlW3ZpJzOIULEIA9VFs+GgNCx+RiKKwsJeUglOT/5dfvdm/fn2dlHfwGFsFMU0uaYzPcoErnbLr6eLhaAUyKFcM9jcE6KzhgYODgPiC2Old1ydaszrOcZfvVvVW8aBU1vatAYDSM9IZlqc7tWeAy023RUDl6X5QvBmrbKJL2VGwdZ0SIXvaNCJBde+1Zt4VcL3igFhaEOPImPUXVkusxQ95QtXUysn9Gn0RgGkXc/9kgx4Gap2ixHbnJovmPOrNE+KoFsMHkh1+81YWpSKBQPPX28XPbdl1hWClt3agC2Ru/lAAx9fit0uByYW1my9IiUB5b/D0C+57ZNs7Buk8bo/7GTi6rlPi2Pt3MIYVoOuSUjONtrDN9nQW8yoWdkju6sj2R4drH6pjPEcWQjja+uK+GyjUB2n0iidzxL0HybswGVAv6m44CWwROt9+AzJF9o1ArszxCUOGOy0NOnTpHwEjkr9smk4BtNhov3cOooABAwCzKtUV9Wp7cCigaBdqGmSJKBYXrqltAMdbWAJzGJrKd6CxVYvXCbsJWKZGpomVhX8pusc8AMAt1tJ9AnxNARo2/cRTCZ7H41HosX25RQoAdLnr78LGSfwbiUhFJBcrLBK702eIoYQ=}
